---
mysql::server::root_password: >
    ENC[PKCS7,MIIBeQYJKoZIhvcNAQcDoIIBajCCAWYCAQAxggEhMIIBHQIBADAFMAACAQEw
    DQYJKoZIhvcNAQEBBQAEggEAnrY9AieG1hBQWLNs7hdlFiU6cwZv1b0aTXkP
    5Az/G/HvS2VHozr4pWKUt+y0y4i9UbULcm3kKESC9wEgwt1qtBGCD62fA+wu
    8YAnqCelqeQNSJ5wwQgYERWIO3HbpG0cqB1AKTyc/WeicP31hrzmkctSWfQN
    B6TnD77EjsD6jgYoIPiDuLUFTKtdhtABJziILpE4xyKIqry0EVcX/YFt7dM6
    Xj8n272UbxmQExx+duGbfDpeQq1l69WlCKaz67+MgFsLE8qljOMtjc/XU6C3
    2UzWJH+lORBzfIuBVpbD7zPeFDIhGphdMtVx1tpn/bHIy4JHgugPg2sOVp2n
    NvR4aTA8BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBBkCQjI8rMPqihHifGy
    /ggmgBAFpTArkYrb/LGYWJpMC2nY]
